
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemv_Fast6464' kernels.
//
// =================================================================================================

namespace clblast {
namespace database {

const DatabaseEntry XgemvFastComplexDouble = {
  "XgemvFast", Precision::kComplexDouble, {"VW2", "WGS2", "WPT2"}, {
    { // AMD GPUs
      kDeviceTypeGPU, "AMD", {
        { "AMD Radeon R9 M370X Compute Engine",              { 1, 256, 1 } },
        { "Ellesmere",                                       { 1, 16, 1 } },
        { "Fiji",                                            { 1, 16, 1 } },
        { "Hawaii",                                          { 1, 64, 1 } },
        { "Oland",                                           { 1, 256, 1 } },
        { "Pitcairn",                                        { 1, 64, 1 } },
        { "Tahiti",                                          { 1, 64, 1 } },
        { "Tonga",                                           { 1, 32, 1 } },
        { "default",                                         { 1, 64, 1 } },
      }
    },
    { // Intel CPUs
      kDeviceTypeCPU, "Intel", {
        { "Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz",       { 4, 32, 4 } },
        { "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz",        { 2, 64, 4 } },
        { "Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz", { 1, 64, 4 } },
        { "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz",         { 4, 64, 4 } },
        { "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",        { 1, 16, 2 } },
        { "default",                                         { 4, 64, 4 } },
      }
    },
    { // Intel accelerators
      kDeviceTypeAccelerator, "Intel", {
        { "Intel(R) Many Integrated Core Acceleration Card", { 1, 64, 1 } },
        { "default",                                         { 1, 64, 1 } },
      }
    },
    { // NVIDIA GPUs
      kDeviceTypeGPU, "NVIDIA", {
        { "GRID K520",                                       { 1, 128, 1 } },
        { "GeForce GTX 480",                                 { 1, 64, 1 } },
        { "GeForce GTX 670",                                 { 1, 64, 1 } },
        { "default",                                         { 1, 64, 1 } },
      }
    },
    { // Default
      kDeviceTypeAll, "default", {
        { "default",                                         { 1, 64, 1 } },
      }
    },
  }
};

} // namespace database
} // namespace clblast
