
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Transpose' kernels.
//
// =================================================================================================

#include "database/database_structure.hpp"

namespace clblast {
namespace database {

extern const DatabaseEntry TransposeHalf;
extern const DatabaseEntry TransposeSingle;
extern const DatabaseEntry TransposeComplexSingle;
extern const DatabaseEntry TransposeDouble;
extern const DatabaseEntry TransposeComplexDouble;

} // namespace database
} // namespace clblast
