
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemv' kernels.
//
// =================================================================================================

#include "database/kernels/xgemv/xgemv.hpp"
#include "database/kernels/xgemv/xgemv_16.hpp"
#include "database/kernels/xgemv/xgemv_32.hpp"
#include "database/kernels/xgemv/xgemv_3232.hpp"
#include "database/kernels/xgemv/xgemv_64.hpp"
#include "database/kernels/xgemv/xgemv_6464.hpp"
