
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemv64' kernels.
//
// =================================================================================================

namespace clblast {
namespace database {

const DatabaseEntry XgemvDouble = {
  "Xgemv", Precision::kDouble, {"WGS1", "WPT1"}, {
    { // AMD GPUs
      kDeviceTypeGPU, "AMD", {
        { "Ellesmere", {
          { "AMD Radeon RX 480",                               { 32, 1 } },
          { "default",                                         { 32, 1 } },
        } },
        { "Fiji", {
          { "AMD Radeon R9 Fury X",                            { 32, 1 } },
          { "AMD Radeon R9 M370X Compute Engine",              { 64, 1 } },
          { "default",                                         { 64, 1 } },
        } },
        { "Hawaii", {
          { "AMD Radeon R9 290X",                              { 128, 1 } },
          { "default",                                         { 128, 1 } },
        } },
        { "Oland", {
          { "Oland",                                           { 256, 1 } },
          { "default",                                         { 256, 1 } },
        } },
        { "Pitcairn", {
          { "AMD Radeon R9 270X",                              { 256, 1 } },
          { "default",                                         { 256, 1 } },
        } },
        { "Tahiti", {
          { "AMD Radeon HD 7970",                              { 256, 1 } },
          { "default",                                         { 256, 1 } },
        } },
        { "Tonga", {
          { "AMD Radeon R9 380",                               { 32, 1 } },
          { "default",                                         { 32, 1 } },
        } },
        { "default", {
          { "default",                                         { 256, 1 } },
        } },
      }
    },
    { // Intel CPUs
      kDeviceTypeCPU, "Intel", {
        { "default", {
          { "Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz",       { 64, 4 } },
          { "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz",        { 64, 2 } },
          { "Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz", { 128, 1 } },
          { "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz",         { 64, 4 } },
          { "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",        { 64, 4 } },
          { "default",                                         { 64, 4 } },
        } },
      }
    },
    { // Intel accelerators
      kDeviceTypeAccelerator, "Intel", {
        { "default", {
          { "Intel(R) Many Integrated Core Acceleration Card", { 64, 1 } },
          { "default",                                         { 64, 1 } },
        } },
      }
    },
    { // NVIDIA GPUs
      kDeviceTypeGPU, "NVIDIA", {
        { "SM2.0", {
          { "GeForce GTX 480",                                 { 256, 1 } },
          { "default",                                         { 256, 1 } },
        } },
        { "SM3.0", {
          { "GRID K520",                                       { 128, 1 } },
          { "GeForce GTX 670",                                 { 128, 1 } },
          { "GeForce GTX 680",                                 { 128, 1 } },
          { "default",                                         { 128, 1 } },
        } },
        { "SM3.5", {
          { "GeForce GTX TITAN",                               { 256, 1 } },
          { "GeForce GTX TITAN Black",                         { 32, 1 } },
          { "Tesla K20m",                                      { 256, 1 } },
          { "Tesla K40m",                                      { 256, 1 } },
          { "default",                                         { 256, 1 } },
        } },
        { "SM5.0", {
          { "GeForce GTX 750",                                 { 64, 1 } },
          { "GeForce GTX 750 Ti",                              { 32, 1 } },
          { "default",                                         { 64, 1 } },
        } },
        { "SM5.2", {
          { "GeForce GTX 980",                                 { 64, 1 } },
          { "GeForce GTX TITAN X",                             { 64, 1 } },
          { "default",                                         { 64, 1 } },
        } },
        { "SM6.1", {
          { "GeForce GTX 1070",                                { 64, 1 } },
          { "GeForce GTX 1080",                                { 32, 1 } },
          { "TITAN X (Pascal)",                                { 32, 1 } },
          { "default",                                         { 128, 1 } },
        } },
        { "default", {
          { "default",                                         { 128, 1 } },
        } },
      }
    },
    { // Default
      kDeviceTypeAll, "default", {
        { "default", {
          { "default",                                         { 128, 1 } },
        } },
      }
    },
  }
};

} // namespace database
} // namespace clblast
