
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemv' kernels.
//
// =================================================================================================

#include "database/database_structure.hpp"

namespace clblast {
namespace database {

extern const DatabaseEntry XgemvHalf;
extern const DatabaseEntry XgemvSingle;
extern const DatabaseEntry XgemvComplexSingle;
extern const DatabaseEntry XgemvDouble;
extern const DatabaseEntry XgemvComplexDouble;

} // namespace database
} // namespace clblast
