
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemv6464' kernels.
//
// =================================================================================================

namespace clblast {
namespace database {

const DatabaseEntry XgemvComplexDouble = {
  "Xgemv", Precision::kComplexDouble, {"WGS1", "WPT1"}, {
    { // AMD GPUs
      kDeviceTypeGPU, "AMD", {
        { "AMD Radeon R9 M370X Compute Engine",              { 64, 1 } },
        { "Ellesmere",                                       { 32, 1 } },
        { "Fiji",                                            { 64, 1 } },
        { "Hawaii",                                          { 64, 1 } },
        { "Oland",                                           { 256, 1 } },
        { "Pitcairn",                                        { 256, 1 } },
        { "Tahiti",                                          { 256, 1 } },
        { "Tonga",                                           { 64, 1 } },
        { "default",                                         { 64, 1 } },
      }
    },
    { // Intel CPUs
      kDeviceTypeCPU, "Intel", {
        { "Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz",       { 64, 4 } },
        { "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz",        { 64, 1 } },
        { "Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz", { 128, 2 } },
        { "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz",         { 64, 4 } },
        { "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",        { 32, 4 } },
        { "default",                                         { 64, 4 } },
      }
    },
    { // Intel accelerators
      kDeviceTypeAccelerator, "Intel", {
        { "Intel(R) Many Integrated Core Acceleration Card", { 64, 1 } },
        { "default",                                         { 64, 1 } },
      }
    },
    { // NVIDIA GPUs
      kDeviceTypeGPU, "NVIDIA", {
        { "GRID K520",                                       { 128, 1 } },
        { "GeForce GTX 480",                                 { 64, 1 } },
        { "GeForce GTX 670",                                 { 128, 1 } },
        { "default",                                         { 128, 1 } },
      }
    },
    { // Default
      kDeviceTypeAll, "default", {
        { "default",                                         { 64, 1 } },
      }
    },
  }
};

} // namespace database
} // namespace clblast
