
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemv3232' kernels.
//
// =================================================================================================

namespace clblast {
namespace database {

const DatabaseEntry XgemvComplexSingle = {
  "Xgemv", Precision::kComplexSingle, {"WGS1", "WPT1"}, {
    { // AMD GPUs
      kDeviceTypeGPU, "AMD", {
        { "AMD Radeon R9 M370X Compute Engine",              { 64, 1 } },
        { "ATI Radeon HD 6750M",                             { 64, 1 } },
        { "Ellesmere",                                       { 32, 1 } },
        { "Fiji",                                            { 32, 1 } },
        { "Hawaii",                                          { 64, 1 } },
        { "Oland",                                           { 64, 1 } },
        { "Pitcairn",                                        { 64, 1 } },
        { "Tahiti",                                          { 64, 1 } },
        { "Tonga",                                           { 32, 1 } },
        { "Turks",                                           { 64, 1 } },
        { "default",                                         { 64, 1 } },
      }
    },
    { // Intel CPUs
      kDeviceTypeCPU, "Intel", {
        { "Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz",       { 32, 4 } },
        { "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz",        { 128, 1 } },
        { "Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz", { 128, 2 } },
        { "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz",         { 64, 4 } },
        { "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",        { 64, 4 } },
        { "default",                                         { 64, 2 } },
      }
    },
    { // Intel GPUs
      kDeviceTypeGPU, "Intel", {
        { "Intel(R) HD Graphics 530",                        { 64, 1 } },
        { "Intel(R) HD Graphics 5500 BroadWell U-Processor GT2", { 64, 1 } },
        { "Intel(R) HD Graphics Haswell Ultrabook GT2 Mobile", { 128, 1 } },
        { "Intel(R) HD Graphics IvyBridge M GT2",            { 256, 1 } },
        { "Intel(R) HD Graphics Skylake ULT GT2",            { 64, 1 } },
        { "Iris",                                            { 256, 1 } },
        { "Iris Pro",                                        { 64, 1 } },
        { "default",                                         { 64, 1 } },
      }
    },
    { // Intel accelerators
      kDeviceTypeAccelerator, "Intel", {
        { "Intel(R) Many Integrated Core Acceleration Card", { 64, 1 } },
        { "default",                                         { 64, 1 } },
      }
    },
    { // NVIDIA GPUs
      kDeviceTypeGPU, "NVIDIA", {
        { "GRID K520",                                       { 256, 1 } },
        { "GeForce GTX 1070",                                { 64, 1 } },
        { "GeForce GTX 1080",                                { 32, 1 } },
        { "GeForce GTX 480",                                 { 64, 1 } },
        { "GeForce GTX 670",                                 { 64, 1 } },
        { "GeForce GTX 680",                                 { 64, 1 } },
        { "GeForce GTX 750",                                 { 128, 1 } },
        { "GeForce GTX 750 Ti",                              { 32, 1 } },
        { "GeForce GTX TITAN",                               { 256, 1 } },
        { "GeForce GTX TITAN Black",                         { 32, 1 } },
        { "TITAN X (Pascal)",                                { 32, 1 } },
        { "default",                                         { 64, 1 } },
      }
    },
    { // Default
      kDeviceTypeAll, "default", {
        { "default",                                         { 64, 1 } },
      }
    },
  }
};

} // namespace database
} // namespace clblast
