
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xconvgemm' kernels.
//
// =================================================================================================

#include "database/database_structure.hpp"

namespace clblast {
namespace database {

extern const DatabaseEntry XconvgemmHalf;
extern const DatabaseEntry XconvgemmSingle;
extern const DatabaseEntry XconvgemmComplexSingle;
extern const DatabaseEntry XconvgemmDouble;
extern const DatabaseEntry XconvgemmComplexDouble;

} // namespace database
} // namespace clblast
