
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xdot64' kernels.
//
// =================================================================================================

namespace clblast {
namespace database {

const DatabaseEntry XdotDouble = {
  "Xdot", Precision::kDouble, {"WGS1", "WGS2"}, {
    { // AMD GPUs
      kDeviceTypeGPU, "AMD", {
        { "Ellesmere", {
          { "AMD Radeon RX 480",                               { 128, 64 } },
          { "default",                                         { 128, 64 } },
        } },
        { "Fiji", {
          { "AMD Radeon R9 Fury X",                            { 256, 32 } },
          { "AMD Radeon R9 M370X Compute Engine",              { 64, 128 } },
          { "default",                                         { 256, 32 } },
        } },
        { "Oland", {
          { "Oland",                                           { 256, 32 } },
          { "default",                                         { 256, 32 } },
        } },
        { "Pitcairn", {
          { "AMD Radeon R9 270X",                              { 128, 32 } },
          { "default",                                         { 128, 32 } },
        } },
        { "Tahiti", {
          { "AMD Radeon HD 7970",                              { 256, 32 } },
          { "default",                                         { 256, 32 } },
        } },
        { "Tonga", {
          { "AMD Radeon R9 380",                               { 128, 64 } },
          { "default",                                         { 128, 64 } },
        } },
        { "default", {
          { "default",                                         { 128, 64 } },
        } },
      }
    },
    { // Intel CPUs
      kDeviceTypeCPU, "Intel", {
        { "default", {
          { "Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz",       { 64, 128 } },
          { "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz",        { 512, 64 } },
          { "Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz", { 64, 64 } },
          { "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",        { 256, 32 } },
          { "default",                                         { 256, 64 } },
        } },
      }
    },
    { // NVIDIA GPUs
      kDeviceTypeGPU, "NVIDIA", {
        { "SM2.0", {
          { "GeForce GTX 480",                                 { 512, 32 } },
          { "default",                                         { 512, 32 } },
        } },
        { "SM3.0", {
          { "GRID K520",                                       { 128, 32 } },
          { "GeForce GTX 670",                                 { 256, 32 } },
          { "GeForce GTX 680",                                 { 128, 64 } },
          { "default",                                         { 256, 64 } },
        } },
        { "SM3.5", {
          { "GeForce GTX TITAN Black",                         { 128, 64 } },
          { "Tesla K20m",                                      { 512, 32 } },
          { "default",                                         { 128, 64 } },
        } },
        { "SM5.0", {
          { "GeForce GTX 750",                                 { 64, 256 } },
          { "GeForce GTX 750 Ti",                              { 128, 64 } },
          { "default",                                         { 64, 256 } },
        } },
        { "SM5.2", {
          { "GeForce GTX 980",                                 { 128, 32 } },
          { "GeForce GTX TITAN X",                             { 256, 32 } },
          { "default",                                         { 256, 32 } },
        } },
        { "SM6.1", {
          { "GeForce GTX 1070",                                { 128, 512 } },
          { "GeForce GTX 1080",                                { 128, 128 } },
          { "TITAN X (Pascal)",                                { 128, 32 } },
          { "default",                                         { 128, 32 } },
        } },
        { "default", {
          { "default",                                         { 128, 128 } },
        } },
      }
    },
    { // Default
      kDeviceTypeAll, "default", {
        { "default", {
          { "default",                                         { 128, 64 } },
        } },
      }
    },
  }
};

} // namespace database
} // namespace clblast
