
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Invert' kernels.
//
// =================================================================================================

#include "database/database_structure.hpp"

namespace clblast {
namespace database {

extern const DatabaseEntry InvertHalf;
extern const DatabaseEntry InvertSingle;
extern const DatabaseEntry InvertComplexSingle;
extern const DatabaseEntry InvertDouble;
extern const DatabaseEntry InvertComplexDouble;

} // namespace database
} // namespace clblast
