
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xger' kernels.
//
// =================================================================================================

#include "database/database_structure.hpp"

namespace clblast {
namespace database {

extern const DatabaseEntry XgerHalf;
extern const DatabaseEntry XgerSingle;
extern const DatabaseEntry XgerComplexSingle;
extern const DatabaseEntry XgerDouble;
extern const DatabaseEntry XgerComplexDouble;

} // namespace database
} // namespace clblast
