
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xger' kernels.
//
// =================================================================================================

#include "database/kernels/xger/xger.hpp"
#include "database/kernels/xger/xger_16.hpp"
#include "database/kernels/xger/xger_32.hpp"
#include "database/kernels/xger/xger_3232.hpp"
#include "database/kernels/xger/xger_64.hpp"
#include "database/kernels/xger/xger_6464.hpp"
