
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemv_Fast_Rot16' kernels.
//
// =================================================================================================

namespace clblast {
namespace database {

const DatabaseEntry XgemvFastRotHalf = {
  "XgemvFastRot", Precision::kHalf, {"VW3", "WGS3", "WPT3"}, {
    { // AMD GPUs
      kDeviceTypeGPU, "AMD", {
        { "Ellesmere", {
          { "AMD Radeon RX 480",                               { 8, 32, 32 } },
          { "default",                                         { 8, 32, 32 } },
        } },
        { "default", {
          { "default",                                         { 8, 32, 32 } },
        } },
      }
    },
    { // Intel GPUs
      kDeviceTypeGPU, "Intel", {
        { "default", {
          { "Intel(R) HD Graphics Skylake ULT GT2",            { 8, 128, 32 } },
          { "default",                                         { 8, 128, 32 } },
        } },
      }
    },
    { // Default
      kDeviceTypeAll, "default", {
        { "default", {
          { "default",                                         { 8, 128, 32 } },
        } },
      }
    },
  }
};

} // namespace database
} // namespace clblast
