
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemv_Fast_Rot' kernels.
//
// =================================================================================================

#include "database/database_structure.hpp"

namespace clblast {
namespace database {

extern const DatabaseEntry XgemvFastRotHalf;
extern const DatabaseEntry XgemvFastRotSingle;
extern const DatabaseEntry XgemvFastRotComplexSingle;
extern const DatabaseEntry XgemvFastRotDouble;
extern const DatabaseEntry XgemvFastRotComplexDouble;

} // namespace database
} // namespace clblast
