
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemm_Direct16' kernels.
//
// =================================================================================================

namespace clblast {
namespace database {

const DatabaseEntry XgemmDirectHalf = {
  "XgemmDirect", Precision::kHalf, {"KWID", "MDIMAD", "MDIMCD", "NDIMBD", "NDIMCD", "PADA", "PADB", "VWMD", "VWND", "WGD"}, {
    { // AMD GPUs
      kDeviceTypeGPU, "AMD", {
        { "Ellesmere",                                       { 8, 32, 8, 8, 32, 1, 1, 1, 1, 32 } },
        { "default",                                         { 8, 32, 8, 8, 32, 1, 1, 1, 1, 32 } },
      }
    },
    { // Intel GPUs
      kDeviceTypeGPU, "Intel", {
        { "Intel(R) HD Graphics Skylake ULT GT2",            { 2, 8, 8, 8, 8, 1, 1, 1, 1, 8 } },
        { "default",                                         { 2, 8, 8, 8, 8, 1, 1, 1, 1, 8 } },
      }
    },
    { // Default
      kDeviceTypeAll, "default", {
        { "default",                                         { 2, 16, 16, 16, 16, 1, 1, 1, 1, 16 } },
      }
    },
  }
};

} // namespace database
} // namespace clblast
