
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemm_Direct64' kernels.
//
// =================================================================================================

namespace clblast {
namespace database {

const DatabaseEntry XgemmDirectDouble = {
  "XgemmDirect", Precision::kDouble, {"KWID", "MDIMAD", "MDIMCD", "NDIMBD", "NDIMCD", "PADA", "PADB", "VWMD", "VWND", "WGD"}, {
    { // AMD GPUs
      kDeviceTypeGPU, "AMD", {
        { "AMD Radeon R9 M370X Compute Engine",              { 2, 16, 16, 8, 8, 1, 1, 1, 1, 16 } },
        { "Ellesmere",                                       { 8, 16, 16, 8, 16, 1, 1, 2, 1, 32 } },
        { "Fiji",                                            { 16, 8, 8, 8, 16, 1, 1, 1, 1, 16 } },
        { "Tonga",                                           { 2, 16, 16, 16, 16, 1, 1, 1, 1, 32 } },
        { "default",                                         { 2, 16, 16, 16, 16, 1, 1, 1, 1, 16 } },
      }
    },
    { // Intel CPUs
      kDeviceTypeCPU, "Intel", {
        { "Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz",       { 2, 8, 8, 8, 8, 1, 1, 4, 4, 32 } },
        { "Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz", { 8, 8, 8, 8, 8, 0, 0, 1, 4, 32 } },
        { "Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz",        { 2, 8, 8, 8, 8, 1, 1, 4, 4, 32 } },
        { "default",                                         { 2, 8, 8, 8, 8, 1, 1, 4, 2, 32 } },
      }
    },
    { // NVIDIA GPUs
      kDeviceTypeGPU, "NVIDIA", {
        { "GeForce GTX 1080",                                { 2, 16, 16, 8, 8, 1, 1, 1, 2, 16 } },
        { "GeForce GTX 750 Ti",                              { 2, 8, 8, 8, 8, 1, 1, 2, 4, 32 } },
        { "GeForce GTX TITAN Black",                         { 8, 16, 16, 16, 8, 1, 0, 1, 1, 16 } },
        { "TITAN X (Pascal)",                                { 2, 8, 8, 8, 8, 1, 1, 1, 1, 16 } },
        { "default",                                         { 2, 8, 8, 8, 8, 1, 1, 1, 2, 16 } },
      }
    },
    { // Default
      kDeviceTypeAll, "default", {
        { "default",                                         { 2, 8, 8, 8, 8, 1, 1, 2, 2, 16 } },
      }
    },
  }
};

} // namespace database
} // namespace clblast
