
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemm_Direct' kernels.
//
// =================================================================================================

#include "database/database_structure.hpp"

namespace clblast {
namespace database {

extern const DatabaseEntry XgemmDirectHalf;
extern const DatabaseEntry XgemmDirectSingle;
extern const DatabaseEntry XgemmDirectComplexSingle;
extern const DatabaseEntry XgemmDirectDouble;
extern const DatabaseEntry XgemmDirectComplexDouble;

} // namespace database
} // namespace clblast
