
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemm_Direct' kernels.
//
// =================================================================================================

#include "database/kernels/xgemm_direct/xgemm_direct.hpp"
#include "database/kernels/xgemm_direct/xgemm_direct_16.hpp"
#include "database/kernels/xgemm_direct/xgemm_direct_32.hpp"
#include "database/kernels/xgemm_direct/xgemm_direct_3232.hpp"
#include "database/kernels/xgemm_direct/xgemm_direct_64.hpp"
#include "database/kernels/xgemm_direct/xgemm_direct_6464.hpp"
