
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Pad' kernels.
//
// =================================================================================================

#include "database/kernels/pad/pad.hpp"
#include "database/kernels/pad/pad_16.hpp"
#include "database/kernels/pad/pad_32.hpp"
#include "database/kernels/pad/pad_3232.hpp"
#include "database/kernels/pad/pad_64.hpp"
#include "database/kernels/pad/pad_6464.hpp"
