
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Copy16' kernels.
//
// =================================================================================================

namespace clblast {
namespace database {

const DatabaseEntry CopyHalf = {
  "Copy", Precision::kHalf, {"COPY_DIMX", "COPY_DIMY", "COPY_VW", "COPY_WPT"}, {
    { // AMD GPUs
      kDeviceTypeGPU, "AMD", {
        { "Ellesmere",                                       { 16, 8, 4, 4 } },
        { "default",                                         { 16, 8, 4, 4 } },
      }
    },
    { // Intel GPUs
      kDeviceTypeGPU, "Intel", {
        { "Intel(R) HD Graphics 5500 BroadWell U-Processor GT2", { 8, 16, 8, 4 } },
        { "Intel(R) HD Graphics Skylake ULT GT2",            { 8, 32, 4, 8 } },
        { "default",                                         { 8, 32, 4, 8 } },
      }
    },
    { // QUALCOMM GPUs
      kDeviceTypeGPU, "QUALCOMM", {
        { "QUALCOMM Adreno(TM)",                             { 32, 8, 8, 1 } },
        { "default",                                         { 32, 8, 8, 1 } },
      }
    },
    { // Default
      kDeviceTypeAll, "default", {
        { "default",                                         { 16, 8, 4, 4 } },
      }
    },
  }
};

} // namespace database
} // namespace clblast
