
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Xgemm' kernels.
//
// =================================================================================================

#include "database/database_structure.hpp"

namespace clblast {
namespace database {

extern const DatabaseEntry XgemmHalf;
extern const DatabaseEntry XgemmSingle;
extern const DatabaseEntry XgemmComplexSingle;
extern const DatabaseEntry XgemmDouble;
extern const DatabaseEntry XgemmComplexDouble;

} // namespace database
} // namespace clblast
