
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Trsv_Routine' kernels.
//
// =================================================================================================

#include "database/database_structure.hpp"

namespace clblast {
namespace database {

extern const DatabaseEntry TrsvRoutineHalf;
extern const DatabaseEntry TrsvRoutineSingle;
extern const DatabaseEntry TrsvRoutineComplexSingle;
extern const DatabaseEntry TrsvRoutineDouble;
extern const DatabaseEntry TrsvRoutineComplexDouble;

} // namespace database
} // namespace clblast
