
// =================================================================================================
// This file is part of the CLBlast project. The project is licensed under Apache Version 2.0. It
// is auto-generated by the 'scripts/database/database.py' Python script.
//
// This file populates the database with best-found tuning parameters for the 'Trsv_Routine' kernels.
//
// =================================================================================================

#include "database/kernels/trsv_routine/trsv_routine.hpp"
#include "database/kernels/trsv_routine/trsv_routine_16.hpp"
#include "database/kernels/trsv_routine/trsv_routine_32.hpp"
#include "database/kernels/trsv_routine/trsv_routine_3232.hpp"
#include "database/kernels/trsv_routine/trsv_routine_64.hpp"
#include "database/kernels/trsv_routine/trsv_routine_6464.hpp"
